apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: rianf@me.com
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # name: letsencrypt-secret-prod
      name: letsencrypt-secret-staging
    solvers:
    - http01:
        ingress:
          class: nginx