apiVersion: v1
type: Opaque
metadata:
  name: orchestra-secrets-source
  namespace: openunison
data:
  K8S_DB_SECRET: emM5ZXFfRTJUSGE4SGtXbnlCeWVoUVVaCg==
  unisonKeystorePassword: YktuQzNkOFdAZkFSSkNra01SOXpHOTlwCg==
  GITHUB_SECRET_ID: ZDRhMThhYzM2MjI4YzE2NWUzM2NkNDc3ZDgzZjk0NmRiMjI1MjNiMAo=
kind: Secret
